name: ViewDistanceTweaks
version: ${version}
main: com.froobworld.viewdistancetweaks.ViewDistanceTweaks
api-version: 1.14
authors: [froobynooby]
description: A plugin that allows for dynamic view distances.
commands:
  vdt:
    description: Base command for the ViewDistanceTweaks plugin.
    aliases: [viewdistancetweaks]
