name: ViewDistanceTweaks
version: ${version}
main: com.froobworld.viewdistancetweaks.ViewDistanceTweaks
api-version: 1.14
authors: [froobynooby]
description: A plugin that allows for dynamic view distances.
softdepend: [PlaceholderAPI]
commands:
  vdt:
    description: Base command for the ViewDistanceTweaks plugin.
    aliases: [viewdistancetweaks]

permissions:
  viewdistancetweaks.vdt.command.*:
    default: op
    description: Access to all /vdt subcommands.
    children:
      viewdistancetweaks.command.vdt: true
      viewdistancetweaks.vdt.command.reload: true
      viewdistancetweaks.vdt.command.status: true
      viewdistancetweaks.vdt.command.set: true
      viewdistancetweaks.vdt.command.set-no-tick: true

  viewdistancetweaks.command.vdt:
    default: op
    description: Access the /vdt command.

  viewdistancetweaks.vdt.command.reload:
    default: op
    description: Access the /vdt reload command.
    children:
      viewdistancetweaks.command.vdt: true

  viewdistancetweaks.vdt.command.status:
    default: op
    description: Access the /vdt status command.
    children:
      viewdistancetweaks.command.vdt: true

  viewdistancetweaks.vdt.command.set:
    default: op
    description: Access the /vdt set command.
    children:
      viewdistancetweaks.command.vdt: true

  viewdistancetweaks.vdt.command.set-no-tick:
    default: op
    description: Access the /vdt set-no-tick command.
    children:
      viewdistancetweaks.command.vdt: true
